export const ACTIONS = {
    SET_JWT_TOKEN: "SET_JWT_TOKEN",
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",

    SET_POSTS: "SET_POSTS",
    SET_SINGLE_POST: "SET_SINGLE_POST",

    SET_USERS: "SET_USERS",
    SET_BOOKMARKS: "SET_BOOKMARKS",
    SEARCH: "SEARCH",
    SET_RESULTS: "SET_RESULTS",

    SET_ERROR: "SET_ERROR",
    RESET_ERROR: "RESET_ERROR",
    SET_LOADING: "SET_LOADING"
};