export const ACTIONS = {
    SET_JWT_TOKEN: "SET_JWT_TOKEN",
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    SET_ERROR: "SET_ERROR",
    RESET_ERROR: "RESET_ERROR",

    SET_POSTS: "SET_POSTS",
    SET_SINGLE_POST: "SET_SINGLE_POST",
};